### ISSUE TITLE
Doesn't compile with linux cmake/gcc 9.3.0

### ISSUE THREAD

**Issue by xervox** [AmusementClub/x265#5]
Hi,
i disabled ENABLE_AVISYNTH = OFF, ENABLE_VPYSYNTH = OFF for linux.
TARGET_CPU = x86-64
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 

could this be fixed?

getting errors like:
abrEncApp.cpp:1114:22: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++11-compat]
 1114 |                 for (auto &&i : m_cliopt->filters)
      |                      ^~~~

abrEncApp.cpp:1114:26: error: expected ‘;’ before ‘&&’ token
 1114 |                 for (auto &&i : m_cliopt->filters)
      |                          ^~~

and cmake policy errors:

CMake Deprecation Warning at CMakeLists.txt:10 (cmake_policy):
   The OLD behavior for policy CMP0025 will be removed from a future version
   of CMake.

   The cmake-policies(7) manual explains that the OLD behaviors of all
   policies are deprecated and that a policy should be set to OLD only under
   specific short-term circumstances.  Projects should be ported to the NEW
   behavior and not rely on setting a policy to OLD.

 CMake Deprecation Warning at CMakeLists.txt:16 (cmake_policy):
   The OLD behavior for policy CMP0054 will be removed from a future version
   of CMake.

   The cmake-policies(7) manual explains that the OLD behaviors of all
   policies are deprecated and that a policy should be set to OLD only under
   specific short-term circumstances.  Projects should be ported to the NEW
   behavior and not rely on setting a policy to OLD.

 CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CheckIncludeFiles.cmake:120 (message):
   Policy CMP0075 is not set: Include file check macros honor
   CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
   details.  Use the cmake_policy command to set the policy and suppress this
   warning.

**Comment by AkarinVS** [comment]
PS: suggested cmake command line when building on linux is:
cmake -B build -GNinja . -DNATIVE_BUILD=ON -DENABLE_AVISYNTH=OFF
-DENABLE_VPYSYNTH=OFF -DCMAKE_ASM_NASM_FLAGS=-w-macro-params-legacy
